"""Add sharing to sessions

Revision ID: 075626a3394a
Revises: eaa875e8df8c
Create Date: 2026-07-25 19:18:40.648080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075626a3394a'
down_revision: Union[str, None] = 'eaa875e8df8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_shared', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('share_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_sessions_share_token'), 'sessions', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_share_token'), table_name='sessions')
    op.drop_column('sessions', 'share_token')
    op.drop_column('sessions', 'is_shared')
    # ### end Alembic commands ###
